version: '3.8'

services:
  airflow-webserver:
    image: apache/airflow:2.8.1
    command: standalone
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__SECRET_KEY: 'dataops-secret-key'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin123
      GCP_PROJECT_ID: dataops-pfa-502611
      GCP_BUCKET_NAME: dataops-pfa-datalake
    volumes:
      - ./src/dataops/orchestration/dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - airflow_db:/opt/airflow
    restart: unless-stopped

volumes:
  airflow_db:
